### ISSUE TITLE
pull pour corriger des erreurs de redirections

### ISSUE THREAD

**Issue by lenaMK** [imglab/atlas-numerique#1]
Salut @emchateau 

J'ai dû faire quelques [corrections](https://github.com/imglab/atlas-numerique/commit/c5df29835ed5e163e507c0e9a5c58af71a4d97a1) pour que les iframes fronctionnent (ajouter le www devant public.archi), pourrais-tu faire un pull depuis le serveur svp?  (branche atlas-2021 si jamais, rien n'a changé côté sous-module donc rien à penser à ce niveau)

C'est le texte que je soumets pour mon dossier d'admission au doctorat donc c'est important que les iframes fonctionnent. 

Merci beaucoup!

**Comment by emchateau** [comment]
Salut, c’est fait.
N’avions-nous pas déjà réglé cela ?
Salutations,
Emmanuel

**Comment by lenaMK** [comment]
Non, j'avais réalisé le problèmes dans mes liens descriptifs mais on n'avait pas mis le site à jour.
Merci!

Je vois une alerte si jamais, il faut mettre à jour le certificat https je crois:
[cid:4c99e147-772b-4dc1-8ca4-bd7d8ac14a16]
________________________________
De : Emmanuel Château-Dutier ***@***.***>
Envoyé : 6 février 2023 03:41
À : imglab/atlas-numerique ***@***.***>
Cc : Lena Krause ***@***.***>; Author ***@***.***>
Objet : Re: [imglab/atlas-numerique] pull pour corriger des erreurs de redirections (Issue #1)


Salut, c’est fait.
N’avions-nous pas déjà réglé cela ?
Salutations,
Emmanuel
